version: "3.8"
services:
  keg-test-consumer:
    image: ${IMAGE}
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - KEG_PROXY_PORT
        - DOC_CORE_PATH
        - DOC_COMPONENTS_PATH
        - DOC_RESOLVER_PATH
        - DOC_RETHEME_PATH
        - DOC_EVF_PATH
        - DOC_JSUTILS_PAT
        - ENV
        - NODE_ENV
    container_name: ${CONTAINER_NAME}
    environment:
      - DOC_APP_PATH
      - KEG_PROXY_PORT
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - KEG_CONSUMER_BUILD_PATH
      - DOC_CORE_PATH
      - DOC_COMPONENTS_PATH
      - DOC_RESOLVER_PATH
      - DOC_RETHEME_PATH
      - DOC_JSUTILS_PAT
      - DOC_EVF_PATH
      - NODE_ENV
