start: /bin/bash /keg/keg-cli/containers/tap/run.sh

env:

  # --- LOCAL ENV CONTEXT --- #
  CORE_PATH: "{{ cli.paths.core }}"
  COMPONENTS_PATH: "{{ cli.paths.components }}"
  RETHEME_PATH: "{{ cli.taps.links.retheme }}"
  JSUTILS_PATH: "{{ cli.paths.jsutils }}"
  RGA_PATH: "{{ cli.taps.links.rga }}"

  # --- KEG-CLI ENV CONTEXT --- #

  # Docker / Docker Compose paths
  KEG_DOCKER_FILE: "{{ cli.taps.links.consumer }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.links.consumer }}/container/values.yml"

  # The default docker-compose file path
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.links.consumer }}/container/docker-compose.yml"

  # The KEG_CONTEXT_PATH env should be the location of the tap being run
  # So it should NOT be set inside the .env file
  KEG_CONTEXT_PATH: "{{ cli.taps.links.consumer }}"
  
  # Image to use when building consumer
  KEG_BASE_IMAGE: ghcr.io/simpleviewinc/tap:master

  # Image to use when running consumer
  KEG_IMAGE_FROM: ghcr.io/simpleviewinc/consumer:master

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the app in the docker container
  DOC_APP_PATH: /keg/app
  DOC_EVF_PATH: /keg/tap
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/tap-resolver
  DOC_JSUTILS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/jsutils
  DOC_RGA_PATH: /keg/app/node_modules/@keg-hub/rga4

  # Default port of the app to expose from the container
  KEG_PROXY_PORT: 3000


  # --- GENERAL CONTEXT ENVs --- #

  # Image/Container Build information
  # IMAGE and CONTAINER_NAME should be the same
  IMAGE: keg-test-consumer
  CONTAINER_NAME: keg-test-consumer
  VERSION: "0.0.1"
  CHOKIDAR_USEPOLLING: 1

  # --- KEG TEST CONSUMER ENVs --- #
  # taps can check this environment variable to determine
  # where to place the build output
  KEG_CONSUMER_BUILD_PATH: /keg/app/node_modules/@keg-hub/tap-evf-sessions
  KEG_EXEC_CMD: start

  # Git tap url in github
  GIT_APP_URL: https://github.com/simpleviewinc/keg-test-consumer.git
  GIT_APP_BRANCH: master