env:

  # --- LOCAL ENV CONTEXT --- #
  CORE_PATH: "{{ cli.paths.core }}"
  COMPONENTS_PATH: "{{ cli.paths.components }}"
  RETHEME_PATH: "{{ cli.taps.links.retheme }}"
  JSUTILS_PATH: "{{ cli.paths.jsutils }}"
  RGA4_PATH: "{{ cli.paths.external }}/apps/rga4"

  # --- KEG-CLI ENV CONTEXT --- #

  # Set the paths to the linked external app
  # The app should be linked to the keg-cli with `kee`
  # Example command to link the app => `keg tap link kee`
  KEG_DOCKER_FILE: "{{ cli.taps.links.consumer }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.links.consumer }}/container/values.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.links.consumer }}/container/docker-compose.yml"

  # The KEG_CONTEXT_PATH env should be the location of the external app being run
  KEG_CONTEXT_PATH: "{{ cli.taps.links.consumer }}"
  KEG_IMAGE_FROM: docker.pkg.github.com/simpleviewinc/keg-packages/keg-test-consumer:develop

  # --- GIT ENV CONTEXT --- #

  GIT_RETHEME_URL: "{{ cli.git.orgUrl }}/keg-test-consumer.git"


  # --- DOCKER ENV CONTEXT --- #

  # Default location of the app in the docker container
  DOC_APP_PATH: /keg/app
  DOC_EVF_PATH: /keg/tap
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/tap-resolver
  DOC_JSUTILS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/jsutils
  DOC_RGA4_PATH: /keg/tap/node_modules/@lancetipton/rga4

  # Default port of the app to expose from the container
  KEG_PROXY_PORT: 3000


  # --- GENERAL CONTEXT ENVs --- #

  # Image/Container Build information
  # IMAGE and CONTAINER_NAME should be the same
  IMAGE: keg-test-consumer
  CONTAINER_NAME: keg-test-consumer
  VERSION: "0.0.1"

  # --- KEG TEST CONSUMER ENVs --- #
  # taps can check this environment variable to determine
  # where to place the build output
  KEG_CONSUMER_BUILD_PATH: /keg/app/node_modules/@keg-hub/tap-evf-sessions
  KEG_FROM_BASE: false
  KEG_EXEC_CMD: start